apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo
  namespace: default
  labels:
    app:  mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mongo
    spec:
    
      containers:
      - name:  mongo
        image:  mongo:4.4.3
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mymongosecret
              key: mongo_db
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mymongosecret
              key: mongo_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mymongosecret
              key: mongo_pass
        ports:
        - containerPort: 27017
          name:  mongo