apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
spec:
  selector:
    app: mongo
  type: LoadBalancer
  ports:
  - name: mongo
    protocol: TCP
    port: 8081
    targetPort: 8081